AWS_ACCESS_KEY_ID = "AKIAIOSFODNN7EXAMPLE123"
AWS_SECRET_ACCESS_KEY = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY123"
API_KEY = "AKIAIOSFODNN7EXAMPLE123!!!!"
API_KEY2 = "AKIAAAADIOSFODNN7EXAMPLE123!!!!"
